[project]
name = "spectra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.0",
    "mermaid-py>=0.8.4",
    "numpy>=2.5.0",
    "pandas>=3.0.3",
    "scikit-learn>=1.9.0",
    "torch>=2.12.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "ipytest>=0.14.2",
    "pytest>=9.1.0",
]
