[project]
name = "spectra"
version = "0.1.0"
description = "BREU2026 Blockchain for Decentralized Science Research Project; A granular provenance recording tool for complex machine learning model training workflows."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.6",
    "pytest>=9.0.3",
    "torch>=2.12.0",
    "test",
    "pyledger",
]

[tool.uv.sources]
pyledger = { workspace = true }
test = { workspace = true }

[tool.uv.workspace]
members = [
    "test",
    "pyledger",
]
